name: Build Status

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: 'microsoft'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK with Gradle
        run: ./gradlew app:assembleDebug
      - name: Uploading APKs
        uses: actions/upload-artifact@v3.1.0
        with:
          name: APKs
          path: app/build/outputs/
